spring.application.name=back-end

spring.datasource.url=jdbc:mysql://172.21.103.45/cms?usessl=false
spring.datasource.username=root

spring.datasource.password=cuW9gHCzU09GY3Eff8soxgbv
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:e8wx61TMUhz6g3LEvgw1jZlK@172.21.91.99/prescriptions?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true


api.path=/api/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M



spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false    
spring.thymeleaf.encoding=UTF-8